title: DaneTheory
description: Just testin' stuff
social_link: '@God_dane'
social_username: DaneTheory
github_repo: DaneTheory/demo
github_username: DaneTheory
theme_color: black
remote_theme: internet-de-france/swiss
baseurl: /demo
defaults:
  - scope:
      path: ''
      type: pages
    values:
      category_name: ''
  - scope:
      path: ''
      type: posts
    values:
      categories: ''
remote_theme_layouts:
  - ''
  - default
  - page
  - post
  - home
  - category_index
social_links:
  - twitter
  - instagram
  - medium
  - dribbble
theme_colors:
  - black
  - blue
  - gray
  - magenta
  - orange
  - red
  - white
  - yellow
